### PR TITLE
WIP: Add badges/shields

### PR DESCRIPTION
**Pull request by olgabot**
To help people scan the list and get a sense of which packages are more popular, I thought it would be a good idea to add badges from http://shields.io for the packages. Since it's a mishmash of Python/R/Bioconductor/matlab/Github/Bitbucket, it's going to be inconsistent between packages, but I still think it would be useful.

This is a work in progress (WIP) as adding each line's badges takes some time and I wanted to know, what do you think?

This may make more sense in a table (started making it [here](https://github.com/olgabot/awesome-single-cell/tree/table) - it's only the headers) so let me know if you think that is better.

### CODE REVIEW

**Comment by seandavi** [comment]
I like it the added value. What do you think in terms of a plan to do everything?  Ask for volunteers?  A table would be nice, also, but I have wondered about whether the extra markup complexity is worth it. Interested in your thoughts.

**Comment by lazappi** [comment]
Just thought I would jump in as I maintain the spreadsheet you mentioned. I think the badges are a great idea and would be happy to contribute to something. I have been thinking that it would be good to have an alternative way of displaying the table (probably via gh-pages) but haven't go around to it. Possibly this could all fit together some how?

**Comment by seandavi** [comment]
I've thought about converting everything to YAML as it is pretty straightforward to edit, allows extension of the data model, and can fully incorporate the information already on the google sheet and in the repo.  Making the transition would be pretty straightforward and could probably be done 95% automatically.  Many website builders can take YAML as input to build a static site. Better yet, YAML is computable, so the site immediately becomes a data resource and can be manipulated with code; adding badges could be done in one swoop.  What do you two think?

**Comment by lazappi** [comment]
I agree that there could be some advantages to a markup format. If that was the case I think there would still need to be some way to convert to/from a table for sorting, filtering etc. I would also have some concerns about completeness and consistency (it is obvious in table when data is missing, or if a new column needs to be added) and making new entries. I haven't really worked much with data in YAML/XML/JSON format so maybe these won't be much of a problem? Personally I was thinking a two step process where data was entered into a table manually then a script run over it to add badges etc. as extra columns. My table is a bit more specific than your page though so I can see how YAML would be the obvious choice in that case.

**Comment by seandavi** [comment]
I added a simple R-based utility (`tools/create_files.R`) that (currently) reads from @lazappi's google sheet and produces a "tidy" CSV format (just cause I could) and, more interestingly, a JSON version.  This version includes notation of Bioconductor, CRAN, and github repo membership.  @olgabot, badges could be added based on this notation.  Since the data are going through R, we can do things like:

- build shiny a shiny app
- create summary graphs, etc, via Rmarkdown
- add info from pubmed (since one can lookup PMID from DOI)
- do simple text mining

**Comment by lazappi** [comment]
I have had a go (with help from some colleagues) at making my table into a website with badges etc. It's probably not ready for general public use yet but I would be keen to get your feedback (not sure this is the appropriate place for that so maybe somewhere else?). https://lazappi.github.io/single-cell-software/

**Comment by seandavi** [comment]
Closing for now. Can revisit at some point, perhaps....

**Pull request closed without merging**
