### PR TITLE
Add PIVOT

### PR DESCRIPTION
**Pull request by eturkes**

### CODE REVIEW

**Comment by seandavi** [comment]
Thanks, @eturkes. Could you do me a favor and revert the second commit so that your relicensing doesn't end up on this repo? Not a big deal, really, but it might end up being confusing.

**Comment by eturkes** [comment]
Whoops! didn't realize my pull request would bring that in too, guess I should've used cherry-pick. I try to relicense forks just cuz it doesn't make sense to have someone else's license in my own repo, and then I place the original license in a NOTICE file, but perhaps it just complicates things...

**Comment by eturkes** [comment]
Hey do you mind closing this and I'll submit a fresh request? Or you can add the ref yourself. Looks like I'm starting to make a mess of my git history trying to squash the commits ha

**Comment by seandavi** [comment]
Sorry to make you jump through hoops! I'll close if that is OK and we can try again.

**Pull request closed without merging**
